#' Plot time series outliers / anomalies
#'
#' @param data data.table object
#' @param value_col value column
#' @param id_col id column
#' @param date_col date column
#' @param outlier_col Outlier/Anomaly column, generated by `detect_outlier()`
#' @param dot_size size of dots in scatterplot
#' @param circle_size size of circles around dots in scatter plots
#' @param arrow_size vector of length 2 for arrow head and -line
#' @param ncol how much columns of plots? Default of 2
#'
#' @import ggplot2
#'
#' @return cowplot object
#' @export
#'
#' @examples
#' \dontrun{
#'   outlier <- detect_outlier(fcf::dow30[ticker == "AAPL",], value_col = "ebit")
#'   plot_outlier(outlier, value_col = "ebit")
#' }
plot_outlier <- function(
  data,
  value_col,
  id_col = "ticker",
  date_col = "date",
  outlier_col = "Outlier",
  dot_size = 1,
  arrow_size = c(0.2, 0.8),
  ncol = 2
) {

  plot_list <- purrr::map(
    unique(data[[id_col]]),
    function(x) {
      d <- data[get(id_col) == x]
      g <- ggplot(d, aes_string(date_col, value_col, group = date_col)) +
        geom_point(aes_string(color = outlier_col), size = dot_size) +
        # geom_point(
        #   aes_string(color = outlier_col),
        #   size = circle_size, shape = 1, alpha = 1,
        #   data = d[get(outlier_col) %in% c("yes", "replacement")]) +
        geom_path(
          arrow = arrow(type = "open", length = unit(arrow_size[1], "cm")),
          colour = "darkgrey", alpha = .8, size = arrow_size[2],
          data = d[get(outlier_col) %in% c("yes", "replacement")]) +
        scale_color_manual(
          values = c("no" = "black", "yes" = "red", "replacement" = "blue")) +
        theme_minimal() +
        theme(legend.position = "none") +
        labs(title = x, x = "", y = "")

      return(g)
    }
  )

  p_temp <- plot_list[[1]] + theme(legend.position = "bottom")
  legend <- cowplot::get_legend(p_temp)
  p_body <- cowplot::plot_grid(plotlist = plot_list, ncol = ncol)
  # p_title <- cowplot::ggdraw() + cowplot::draw_label("title", size = 18, fontface = "bold")

  cowplot::plot_grid(cowplot::ggdraw(), p_body, legend, ncol = 1, rel_heights = c(0.05, 1, 0.05))
}
